<style>
    * {
        padding: 0;
        margin: 5px;
        text-align: center;
    }
    body {
        background-color:blue;
    }
    .calculator {
        width: 350px;
        height: 320px;
        background-color: #c0c0c0;
        box-shadow: 0px 0px 0px 10px #666;
        border: 5px solid black;
        border-radius: 10px;
    }
    #display {
        width: 320px;
        height: 40px;
        text-align: right;
        background-color: black;
        border: 3px solid white;
        font-size: 18px;
        left: 2px;
        top: 2px;
        color: #7fff00;
    }
    .btnTop{
        color: white;
        background-color: #6f6f6f;
        font-size: 14px;
        margin: auto;
        width: 50px;
        height: 25px;
    }
    .btnNum {
        color: white;
        background-color: black;
        font-size: 14px;
        margin: auto;
        width: 50px;
        height: 25px;
    }
    .btnMath {
        color: white;
        background-color: #ff4561;
        font-size: 14px;
        margin: auto;
        width: 50px;
        height: 25px;
    }
    .btnOpps {
        color: white;
        background-color: #ff9933;
        font-size: 14px;
        margin: auto;
        width: 50px;
        height: 25px;
    }
</style>

<script>
    function addChar(input, character)
    {
        if (input.value == null || input.value == "0")
            input.value = character
        else
            input.value += character
    }

    function sqrt(form) {
        form.display.value = Math.sqrt(form.display.value);
    }

    function deleteChar(input)
    {
        input.value = input.value.substring(0, input.value.length - 1)
    }

    let val = 0.0;

    function percent(input)
    {
        val = input.value;
        input.value = input.value + "%";
    }

    function doOperation(form)
    {
        form.submit();
        form.display.value = eval(form.display.value);
    }

    function checkNum(str)
    {
        for (let i = 0; i < str.length; i++) {
            let ch = str.charAt(i);
            if (ch < "0" || ch > "9") {
                if (ch != "/" && ch != "*" && ch != "+" && ch != "-" && ch != "."
                    && ch != "(" && ch!= ")" && ch != "%") {
                    alert("invalid entry!")
                    return false
                }
            }
        }
        return true
    }
</script>


<div class="container">


    <form name="sci-calc" action="/calculator" method="post">
        <table class="calculator" cellspacing="0" cellpadding="1">
            <tr>
                <td colspan="5"><input id="display" name="display" value="0" size="28" maxlength="25"></td>
            </tr>
            <tr>
                <td><input type="button" class="btnTop" name="btnTop" value="C" onclick="this.form.display.value=  0 "></td>
                <td><input type="button" class="btnTop" name="btnTop" value="DEL" onclick="deleteChar(this.form.display)"></td>
                <td><input type="button" class="btnMath" name="btnOpps" value="&radic;" onclick="if(checkNum(this.form.display.value)) { sqrt(this.form) }"></td>
                <td><input type="button" class="btnMath" name="btnMath" value="%" onclick=" percent(this.form.display)"></td>
            </tr>
            <tr>
                <td><input type="button" class="btnNum" name="btnNum" value="7" onclick="addChar(this.form.display, '7')"></td>
                <td><input type="button" class="btnNum" name="btnNum" value="8" onclick="addChar(this.form.display, '8')"></td>
                <td><input type="button" class="btnNum" name="btnNum" value="9" onclick="addChar(this.form.display, '9')"></td>
                <td><input type="button" class="btnMath" name="btnMath" value="/" onclick="addChar(this.form.display, '/')"></td>
            <tr>
                <td><input type="button" class="btnNum" name="btnNum" value="4" onclick="addChar(this.form.display, '4')"></td>
                <td><input type="button" class="btnNum" name="btnNum" value="5" onclick="addChar(this.form.display, '5')"></td>
                <td><input type="button" class="btnNum" name="btnNum" value="6" onclick="addChar(this.form.display, '6')"></td>
                <td><input type="button" class="btnMath" name="btnMath" value="*" onclick="addChar(this.form.display, '*')"></td>
            </tr>
            <tr>
                <td><input type="button" class="btnNum" name="btnNum" value="1" onclick="addChar(this.form.display, '1')"></td>
                <td><input type="button" class="btnNum" name="btnNum" value="2" onclick="addChar(this.form.display, '2')"></td>
                <td><input type="button" class="btnNum" name="btnNum" value="3" onclick="addChar(this.form.display, '3')"></td>
                <td><input type="button" class="btnMath" name="btnMath" value="-" onclick="addChar(this.form.display, '-')"></td>
            </tr>
            <tr>
                <td><input type="button" class="btnNum" name="btnNum" value="0" onclick="addChar(this.form.display, '0')"></td>
                <td><input type="button" class="btnNum" name="btnNum" value="&#46;" onclick="addChar(this.form.display, '&#46;')"></td>
                <td><input type="button" class="btnTop" name="btnTop" value="=" onclick="if(checkNum(this.form.display.value)) { doOperation(this.form) }"></td>
                <td><input type="button" class="btnMath" name="btnMath" value="+" onclick="addChar(this.form.display, '+')"></td>
            </tr>
            <tr>
                <td><input type="button" class="btnMath" name="btnMath" value="(" onclick="addChar(this.form.display, '(')"></td>
                <td><input type="button" class="btnMath" name="btnMath" value=")" onclick="addChar(this.form.display,')')"></td>
                <td><input type="button" class="btnMath" name="btnOpps" value=" " disabled></td>
                <td><input type="button" class="btnMath" name="btnMath" value=" " disabled></td>
            </tr>
        </table>
    </form>

</div>

