<script src="src/Ebanx/Views/user/login.js"></script>
<link href="src/Ebanx/Views/user/login.css" rel="stylesheet">

<div id="fullscreen_bg" class="fullscreen_bg"/>
<div class="container">
    <form class="form-signin" id="frmSignin">
        <h1 class="form-signin-heading">Calculadora</h1>
        <input id="login" type="text" class="form-control" placeholder="Login" required autofocus>
        <input id="password" type="password" class="form-control" placeholder="Senha" required>
        <a class="form-signin-heading"href="">Criar uma conta</a>
        <button class="btn btn-lg btn-primary btn-block"  onclick="validate(event)">
            Entrar
        </button>
    </form>

</div>