<style type="text/css">
    .login-form {
        width: 340px;
        margin: 50px auto;
    }
    .login-form form {
        margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {
        font-size: 15px;
        font-weight: bold;
    }
</style>

<div class="login-form">
    <form action="/user-validate" method="post">
        <h2 class="text-center">Prova Ebanx</h2>
        <div class="form-group">
            <input type="text" name="login" class="form-control" placeholder="Login" required="required">
        </div>
        <div class="form-group">
            <input type="password" name="password" class="form-control" placeholder="Senha" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Entrar</button>
        </div>
    </form>
    <p class="text-center"><a href="/user-new">Criar uma conta</a></p>
</div>